[pica]
secretKey = "~d}$Q7$eIni=V)9\\RK/P.RM4;9[7|@/CA}b~OW!3?EV`:<>M7pddUBL5n|0/*Cn"

[pica.headers]
apiKey = "C69BAF41DA5ABD1FFEDC6D2FEA56B"

appVersion = "2.2.1.3.3.4"
appChannel = "3"
buildVersion = "45"
appPlatform = "android"

accept = "application/vnd.picacomic.com.v1+json"
userAgent = "okhttp/3.8.1"
contentType = "application/json; charset=UTF-8"

imageQuality = "original"


[server]
port = ":9002"
allowRememberToken = true